#! /bin/bash

# Install NGINX web server
mkdir -p ~/tmp && cd ~/tmp
wget http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz
tar -zxvf nginx-$NGINX_VERSION.tar.gz
cd nginx-$NGINX_VERSION
./configure --prefix=/etc/nginx --sbin-path=/usr/local/sbin --with-http_ssl_module
make && make install

# Add nginx restart file
cd /etc/init.d && wget --no-check-certificate https://raw.github.com/meskyanichi/provisioner/master/lib/nginx/nginx
chmod +x /etc/init.d/nginx

# make sites-enabled, logs and tmp/pids directories
mkdir -p /etc/nginx/logs /etc/nginx/tmp/pids /etc/nginx/conf/sites-enabled

# replace default nginx configuration
rm /etc/nginx/conf/nginx.conf
cd /etc/nginx/conf && wget --no-check-certificate https://raw.github.com/meskyanichi/provisioner/master/lib/nginx/nginx.conf

# start nginx automatically when the system boots
/usr/sbin/update-rc.d -f nginx defaults