#! /bin/bash

# Install NGINX web server
mkdir -p ~/tmp && cd ~/tmp
wget http://nginx.org/download/nginx-$NGINX_VERSION.tar.gz
tar -zxvf nginx-$NGINX_VERSION.tar.gz
cd nginx-$NGINX_VERSION
./configure --prefix=/etc/nginx --sbin-path=/usr/local/sbin --with-http_ssl_module
make && make install

# Add nginx restart file
cd /etc/init.d && wget --no-check-certificate https://github.com/meskyanichi/provisioner/raw/master/lib/nginx/nginx
chmod +x /etc/init.d/nginx

# make sites-enabled, logs and tmp/pids directories
mkdir -p /etc/nginx/logs/
mkdir -p /etc/nginx/tmp/pids/
mkdir -p /etc/nginx/conf/sites-enabled

# replace default nginx configuration
rm /etc/nginx/conf/nginx.conf
cd /etc/nginx/conf && wget --no-check-certificate https://github.com/meskyanichi/provisioner/raw/master/lib/nginx/nginx.conf