#! /bin/bash

# Ensure nothing is prompted during installation
export DEBIAN_FRONTEND=noninteractive

# Install MySQL client and server
aptitude install -y mysql-client mysql-server libmysqlclient15-dev mysql-common

# to-do
# set default encoding to UTF8