#! /bin/bash

install(){
  curl https://github.com/meskyanichi/provisioner/raw/master/lib/$1/provision | bash
}

## Basic package updates, upgrades and new installations

# Install aptitude package manager
apt-get update -y
apt-get install -y aptitude

# Update and upgrade package list
aptitude update -y
aptitude upgrade -y

# Install a bunch of necessary packages
aptitude install -y \
  gcc g++ build-essential bison openssl libreadline6 libreadline6-dev \
  htop git-core curl wget ufw tree rsync zlib1g zlib1g-dev libssl-dev \
  libyaml-dev libxml2-dev libxslt-dev autoconf libpcre3 libpcre3-dev libpcrecpp0 \
  libc6-dev ncurses-dev


## Modules - Uncomment the modules you'd like to install

##
# Ruby Version Manager module
#
# export RVM_RUBY_VERSION=1.9.2
# install rvm

##
# Deployment User module
#
# export DEPLOYER_USERNAME=deployer
# export DEPLOYER_PASSWORD=qwerty
# install deployer

##
# NGINX module
#
# export NGINX_VERSION=1.0.2
# install nginx

##
# MySQL module
#
# install mysql

##
# PostgreSQL module
#
# install postgresql

##
# SQLite module
#
# install sqlite

##
# MongoDB module
#
# export MONGODB_VERSION=1.8.1
# install mongodb

##
# Redis module
#
# install redis

##
# Node.js module
#
# install nodejs

##
# ImageMagick module
#
# install imagemagick

##
# FFMpeg module
#
# install ffmpeg

## Security module
#
# export SECURITY_PORT=22
# install security