#! /bin/bash

# Install MRI dependencies
aptitude install -y libsqlite3-0 libsqlite3-dev sqlite3

# Install JRuby dependencies
aptitude install -y openjdk-6-jre-headless

# Install RVM as root (system-wide install)
bash < <(curl -s https://rvm.beginrescueend.com/install/rvm)

# Adjust the ~/.bashrc file for RVM
if [[ $(cat ~/.bashrc) != */usr/local/rvm/scripts/rvm* ]]; then
  sed -i "s/^\[ -z \"\$PS1\" \] \&\& return/# \[ -z \"\$PS1\" \] \&\& return\n\nif \[\[ -n \"\$PS1\" \]\]; then/" ~/.bashrc
  echo -e "\nfi" >> ~/.bashrc
  echo -e "\n\n[[ -s \"/usr/local/rvm/scripts/rvm\" ]] && source \"/usr/local/rvm/scripts/rvm\"" >> ~/.bashrc
  source ~/.bashrc
fi

# Install RVM_RUBY_VERSION
rvm install $RVM_RUBY_VERSION
rvm use $RVM_RUBY_VERSION --default

# Add a .gemrc file to improve gem installation speed
curl https://raw.github.com/meskyanichi/provisioner/master/lib/rvm/gemrc > ~/.gemrc

# Install latest bundler version so we can install all application gems
gem install bundler

# Install Bluepill for process monitoring
gem install bluepill
mkdir -p /var/bluepill && chown -R $DEPLOYER_USERNAME:www-data /var/bluepill

# Install Backup for performing backups
gem install backup

# Ensure the deployment user is added to the RVM group
usermod -G rvm $DEPLOYER_USERNAME