#! /bin/bash

## Ruby Version Manager

# Install RVM as root (system-wide install)
bash < <(curl -s https://rvm.beginrescueend.com/install/rvm)

# Adjust the ~/.bashrc file for RVM
sed -i "s/^\[ -z \"\$PS1\" \] \&\& return/# \[ -z \"\$PS1\" \] \&\& return\n\nif \[\[ -n \"\$PS1\" \]\]; then/" ~/.bashrc
echo -e "\nfi" >> ~/.bashrc
echo -e "\n\n[[ -s \"/usr/local/rvm/scripts/rvm\" ]] && source \"/usr/local/rvm/scripts/rvm\"" >> ~/.bashrc
source ~/.bashrc

# Ensure latest (stable) RVM version is installed
rvm get latest
rvm reload

# Install latest MRI Ruby (1.9.2)
rvm install 1.9.2
rvm use 1.9.2 --default

# Add a .gemrc file to improve gem installation speed
curl https://gist.github.com/raw/972787/3745b31a17ebe846411b281f5bc2da7ecaec5035/gemrc > ~/.gemrc

# Install latest bundler version so we can install all gems via Bundler
gem install bundler