#! /bin/bash

## Ruby Version Manager

# Install MRI dependencies
aptitude install -y libsqlite3-0 libsqlite3-dev sqlite3

# Install JRuby dependencies
aptitude install -y openjdk-6-jre-headless

# Install RVM as root (system-wide install)
bash < <(curl -s https://rvm.beginrescueend.com/install/rvm)

# Adjust the ~/.bashrc file for RVM
if [[ $(cat ~/.bashrc) != */usr/local/rvm/scripts/rvm* ]]; then
  sed -i "s/^\[ -z \"\$PS1\" \] \&\& return/# \[ -z \"\$PS1\" \] \&\& return\n\nif \[\[ -n \"\$PS1\" \]\]; then/" ~/.bashrc
  echo -e "\nfi" >> ~/.bashrc
  echo -e "\n\n[[ -s \"/usr/local/rvm/scripts/rvm\" ]] && source \"/usr/local/rvm/scripts/rvm\"" >> ~/.bashrc
  source ~/.bashrc
fi

# Ensure latest (stable) RVM version is installed
rvm get latest
rvm reload

# Install latest MRI Ruby (1.9.2)
rvm install 1.9.2
rvm use 1.9.2 --default

# Add a .gemrc file to improve gem installation speed
curl https://github.com/meskyanichi/provisioner/raw/master/lib/rvm/gemrc > ~/.gemrc

# Install latest bundler version so we can install all gems via Bundler
gem install bundler