#! /bin/bash

# Change SSH port from 22 to $SECURITY_PORT
# so the deployment user can only log in via port '$SECURITY_PORT'
sed -i "s/Port 22/Port $SECURITY_PORT/" /etc/ssh/sshd_config
/etc/init.d/ssh reload

# Set up firewall to whitelist ports
ufw allow $SECURITY_PORT # ssh port
ufw allow 80             # nginx http port
ufw allow 443            # nginx https port
ufw --force enable # enable without prompt

# disable root password - log in via the deployment user and
# run 'sudo su' to log in as root from now on
passwd -l root